title = "Lauren Cerand"
DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
buildFuture = true
baseURL = "https://www.laurencerand.com"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
disableKinds = ["taxonomy", "taxonomyTerm"]
themesDir = "layout_modules"
theme = "hugo-layout_module-base"
[mediaTypes]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]


[outputFormats]

[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

[outputFormats.REDIR]
baseName = "_redirects"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

[outputs]
home = [
"HTML",
"HEADERS",
"REDIR"
]

[params]
description = "The personal website of Lauren Cerand"
logo = "/uploads/2020-09-01-lauren-2.jpg"
images = ["/uploads/2021-02-24-lauren.jpg"]


[social]
